// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG9sFw4rsygVCVf3ky7mxcw4EocLnHGEw',
    appId: '1:1004616236724:web:86c0cc42c16053592a61e1',
    messagingSenderId: '1004616236724',
    projectId: 'blogit-a5008',
    authDomain: 'blogit-a5008.firebaseapp.com',
    storageBucket: 'blogit-a5008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmNJEY4yNec2gYzrcwwhwFvpFNxDmoEo',
    appId: '1:1004616236724:android:e002c7d191f0e1f52a61e1',
    messagingSenderId: '1004616236724',
    projectId: 'blogit-a5008',
    storageBucket: 'blogit-a5008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDicQD_xFjI26DiUTeD7YkkW4-OCFO-6sk',
    appId: '1:1004616236724:ios:7379a0f5c448afe82a61e1',
    messagingSenderId: '1004616236724',
    projectId: 'blogit-a5008',
    storageBucket: 'blogit-a5008.appspot.com',
    iosClientId: '1004616236724-ritt0tf0omkv2djmtg60ana8q4omjoua.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDicQD_xFjI26DiUTeD7YkkW4-OCFO-6sk',
    appId: '1:1004616236724:ios:7379a0f5c448afe82a61e1',
    messagingSenderId: '1004616236724',
    projectId: 'blogit-a5008',
    storageBucket: 'blogit-a5008.appspot.com',
    iosClientId: '1004616236724-ritt0tf0omkv2djmtg60ana8q4omjoua.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogit',
  );
}
